Calculate components and SHAP using empirical probabilities by default
PlantedML/glex pull request #17
Opened 2024-03-15 09:58 UTC by jyliuu

This PR includes changes to the `glex` function. 
- `glex` is now able to take ranger objects as input
- `glex` has a new optional parameter `probFunction` which specifies the probability function to use for weighting/marginalization of the leaves. If left to NULL, it will default to using the empirical marginal probabilities. Otherwise it can either be set to "path-dependent", i.e. using old weighting or to a custom probability function of the signature `function(coords, lb, ub)`
- Added some miscellaneous code for simulations under simulations/

2024-03-15 10:59 UTC, jemus42 reviewed
Should `simulation/` really be included in the repo? 
This seems like something that should go into a separate project rather than the package?

2024-03-15 12:06 UTC, MHiabu commented
I agree that `simulation/` should be rather taken out.

2024-03-15 13:41 UTC, jemus42 requested changes
Cool 👍🏻 

Just a few things here and there for cleaning up.

2024-03-15 13:41 UTC, jemus42 commented on R/glex.R
> +#' @param features Vector of column names in x to calculate components for. If \code{NULL}, all features are used.
Maybe explicitly state that the default is `NULL` -> all features

2024-03-15 13:41 UTC, jemus42 commented on R/glex.R
> +#' @param probFunction Either "path-dependent" to use old path-dependent weighting of leaves or a user specified probability function of the signature function(coords, lb, ub). If left null, the empi
Similarly here --- I usually try to make "what's the default value" the first thing in the parameter docs

2024-03-15 13:41 UTC, jemus42 commented on R/glex.R
> +tree_fun_old <- function(tree, trees, x, all_S) {
Maybe rename this to something more informative? Functions with `_old` suffixes tend to just make me assume they're obsolete or deprecated, which doesn't appear to be the case here.

Thanks for prying out the internal functions though 😬

2024-03-15 13:41 UTC, jemus42 commented on R/glex.R
> +  if (is.character(probFunction) && probFunction == "path-dependent")
Is it necessary to if/else here depending on `probFunction`, which is passed to `tree_fun_emp()` anyway if it's not equal to `"path-dependent"`? 

I mean, would it be simpler to have just one `tree_fun` that takes a `probFunction` argument and then internally switches behavior?

2024-03-15 13:41 UTC, jemus42 commented on tests/testthat/test-glex-xgboost.R
These test now produce verbose output, flooding my console and the test pane:

```r
[1] "tree 0 of 49"
[1] "tree 1 of 49"
[1] "tree 2 of 49"
[1] "tree 3 of 49"
[1] "tree 4 of 49"
[1] "tree 5 of 49"
[1] "tree 6 of 49"
[1] "tree 7 of 49"
[1] "tree 8 of 49"
[1] "tree 9 of 49"
[1] "tree 10 of 49"
[1] "tree 11 of 49"
[1] "tree 12 of 49"
...
```

If this is debug output and no longer required please remove it, or if necessary put it behind some global option (e.g. `options(glex.verbose = TRUE)` or something) such that it is not shown by default.

2024-03-16 11:01 UTC, jyliuu commented on R/glex.R
> +  if (is.character(probFunction) && probFunction == "path-dependent")
Well, the path_dependent tree_fun doesn't take a probFunction as argument, so that's the reason for the split

2024-03-16 11:03 UTC, jyliuu commented
I have refactored the commit graph such that all commits related to `simulation/` have been removed 😅, and I have also committed your suggestions @jemus42. 

- Best regards

2024-03-16 12:58 UTC, jemus42 commented on R/theme_glex.R
Nice addition, thanks!

2024-03-16 13:01 UTC, jemus42 commented on R/glex.R
> +  if (is.character(probFunction) && probFunction == "path-dependent")
But that's my point - I was wondering if it was easier to have one `tree_fun()` that takes `probFunction` as an argument and then can either act as the path-dependent version (e.g. if `probFunction = NULL`?) or as currently `tree_fun_emp()` does.

I'm not saying it should be, just asking whether you think that would be easier/neater in the long run ¯\\\_(ツ)_/¯

2024-03-16 13:06 UTC, jemus42 commented on debug.r
Thanks for removing the `simulation` bit but I think the `debug` bit also shouldn't be here right? 😅

2024-03-16 13:12 UTC, jemus42 commented on R/glex.R
> +  if (is.character(probFunction) && probFunction == "path-dependent")
Come to think of it: Regardless of how many `tree_fun_*`s there are, would you mind adding a basic roxygen skeleton for them? I know they are internal functions and not meant to be user-facing, but personally I think it is always helpful to have a few things documented for internal functions of a given complexity, especially input types and return value.

In this case for example I can mostly guess what the inputs are: `tree`, `trees`, `x`, `all_S` --- I can tell `trees` is a `data.table` and `tree` likely an integer but that's about it 🙃

2024-03-16 13:14 UTC, jemus42 commented on NEWS.md
Almost forget: Don't forget to add your changes to the NEWS 😬

2024-03-16 13:15 UTC, jemus42 commented on DESCRIPTION
Oh and please add yourself as an author (`role = "aut"`) here!

2024-03-17 11:21 UTC, MHiabu commented on R/glex.R
> +  if (is.character(probFunction) && probFunction == "path-dependent")
Apart from that: `probFunction = "empirical"` should do the same as `probFunction = NULL` .
And if probFunction not in \{NULL, "empirical"\} or a prob function, it should give an error.

2024-03-17 14:14 UTC, jyliuu commented on debug.r
Yes, good catch :)

2024-03-17 14:19 UTC, jyliuu commented on R/glex.R
> +  if (is.character(probFunction) && probFunction == "path-dependent")
Okay, I think I understand. I will just extract the if-statement into a separate function called tree-fun, which returns a closure (the actual treeFun) based on the specified probFunction.

2024-03-17 14:41 UTC, jyliuu commented on DESCRIPTION
Not sure how to do that haha

2024-03-17 14:42 UTC, jyliuu commented on NEWS.md
Should I then bump the version or?

2024-03-17 15:51 UTC, MHiabu approved these changes

2024-03-17 15:51 UTC, MHiabu commented on NEWS.md
good with me.

2024-03-17 23:32 UTC, jemus42 commented on NEWS.md
Yeah this is a minor version bump, 0.4.0

2024-03-17 23:35 UTC, jemus42 commented on DESCRIPTION
See the `DESCRIPTION` file and add a line in the `Authors@R` field, similar to e.g. Munir's `person("Munir", "Hiabu", role = "aut"),` with your info, optionally with your ORCID if you want (see my entry in that field).

2024-03-18 15:37 UTC, jemus42 approved these changes

2024-03-18 15:38 UTC, jemus42 commented
Yeah turns out I messed up the versioning and told you the wrong thing, sorry.
This should bump glex 0.3.0.9000 -> glex 0.4.0 and I should tag a release, but don't worry about it I'll just do this minor maintenance stuff after merging this.

Anyway, sorry for the holdup, I'll merge this now, thanks! 👍🏻

2024-03-18 15:38 UTC, merged